app/urls.py
from django.contrib import admin
from django.urls import path
#------------------------------------------------------
from .views import home, error, error_deleted, pdf_, ask
from .views import cv_show, cv_show_edit
#ADD
from .views import add_bio
# from .views import add_edu, add_job, add_jobrole, add_jobrolecat
# from .views import add_lang, add_web, add_intro, add_skill1, add_skill2
#ADD ONLY
from .views import add_job_only, add_jobrole_only, add_jobrolecat_only, add_edu_only
from .views import add_lang_only, add_web_only, add_intro_only, add_skill1_only, add_skill2_only
#EDIT
from .views import edit_bio, edit_lang, edit_web, edit_skill1, edit_skill2, edit_intro
from .views import edit_job, edit_jobrole, edit_jobrolecat, edit_edu, edit_color
#DELETES
from .views import delete_lang, delete_web, delete_skill1, delete_skill2, delete_intro, delete_intro
from .views import delete_job, delete_edu, delete_cv, delete_jobrole, delete_jobrolecat
from user_auth.views import password_reset_req


#from .views import  add_jobrole_back, add_jobrolecat_back, add_job_back,add_edu_back, add_bio_back


urlpatterns = [
    path('', home, name='home'),
    path('pdf_',pdf_, name = 'pdf_'),
    path('ask/',ask, name = 'ask'),

    path('error', error, name='error'),
    path('error/', error_deleted, name='error_deleted'),

    path('cv/<str:pk>', cv_show ,name='cv_show'),
    path('cv_edit/<str:pk>', cv_show_edit ,name='cv_show_edit'),

    #ADD
    path('add_bio/<str:pk>', add_bio, name='add_bio'),
    # path('add_lang/<str:pk>/<str:x>/<int:y>', add_lang, name='add_lang'),
    # path('add_web/<str:pk>/<str:x>/<int:y>', add_web, name='add_web'),
    # path('add_skill1/<str:pk>/<str:x>/<int:y>', add_skill1, name='add_skill1'),
    # path('add_skill2/<str:pk>/<str:x>/<int:y>', add_skill2, name='add_skill2'),
    # path('add_intro/<str:pk>/<str:x>/<int:y>', add_intro, name='add_intro'),

    # path('add_job/<str:pk>/<str:x>/<int:y>', add_job, name='add_job'),
    # path('add_job_r/<str:pk>/<str:x>/<int:y>', add_jobrole, name='add_jobrole'),
    # path('add_jobb_r_c/<str:pk>/<str:x>/<int:y>', add_jobrolecat, name='add_jobrolecat'),

    # path('add_edu/<str:pk>/<str:x>/<int:y>', add_edu, name='add_edu'),
    

    #ADD ONLY
    path('add_lang_/<str:pk>', add_lang_only, name='add_lang_only'),
    path('add_web_/<str:pk>', add_web_only, name='add_web_only'),
    path('add_skill1_/<str:pk>', add_skill1_only, name='add_skill1_only'),
    path('add_skill2_/<str:pk>', add_skill2_only, name='add_skill2_only'),
    path('add_intro_/<str:pk>', add_intro_only, name='add_intro_only'),

    path('add_job_/<str:pk>', add_job_only, name='add_job_only'),
    path('add_jr_/<str:pk>', add_jobrole_only, name='add_jobrole_only'),
    path('add_jrc_/<str:pk>', add_jobrolecat_only, name='add_jobrolecat_only'),

    path('add_edu_/<str:pk>', add_edu_only, name='add_edu_only'),

    #EDIT
    path('edit_color/<str:pk>', edit_color, name='edit_color'),
    path('edit_bio/<str:pk>', edit_bio, name='edit_bio'),
    path('edit_lang/<str:pk>', edit_lang, name='edit_lang'),
    path('edit_web/<str:pk>', edit_web, name='edit_web'),
    path('edit_skill1/<str:pk>', edit_skill1, name='edit_skill1'),
    path('edit_skill2/<str:pk>', edit_skill2, name='edit_skill2'),
    path('edit_intro/<str:pk>', edit_intro, name='edit_intro'),

    path('edit_job/<str:pk>', edit_job, name='edit_job'),
    path('edit_jr/<str:pk>', edit_jobrole, name='edit_jobrole'),
    path('edit_jrc/<str:pk>', edit_jobrolecat, name='edit_jobrolecat'),
    path('edit_edu/<str:pk>', edit_edu, name='edit_edu'),

    #DELETE
    path('delete_cv/<str:pk>', delete_cv, name='delete_cv'),
    path('delete_lang/<str:pk>', delete_lang, name='delete_lang'),
    path('delete_web/<str:pk>', delete_web, name='delete_web'),
    path('delete_skill1/<str:pk>', delete_skill1, name='delete_skill1'),
    path('delete_skill2/<str:pk>', delete_skill2, name='delete_skill2'),
    path('delete_intro/<str:pk>', delete_intro, name='delete_intro'),

    path('delete_j/<str:pk>', delete_job, name='delete_job'),
    path('delete_jr/<str:pk>', delete_jobrole, name='delete_jobrole'),
    path('delete_jrc/<str:pk>', delete_jobrolecat, name='delete_jobrolecat'),
    path('delete_edu/<str:pk>', delete_edu, name='delete_edu'),

    path('delete_intro/<str:pk>', delete_intro, name='delete_intro'),


   

]

'''    #ADD BACK
    
 
    path('add_jr_b/<str:pk>/<str:x>/<int:y>', add_jobrole_back, name='add_jobrole_back'),
    path('add_jrc_b/<str:pk>/<str:x>/<int:y>', add_jobrolecat_back, name='add_jobrolecat_back'),

    path('add_edu_b/<str:pk>/<str:x>/<int:y>', add_edu_back, name='add_edu_back'),
    path('add_bio_b/<str:pk>/<str:x>/<int:y>', add_bio_back, name='add_bio_back'),
'''

cheekycv_new_1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('user_auth/',include('django.contrib.auth.urls')),
    path('user_auth/',include('user_auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from .views import UserRegisterView,CustomLoginView, PasswordsChangeView, success, UserEditView, delete_pic, password_reset_req, err
from .views import ShowProfPageView, EditProfPageView, CreateProfilePageView
#from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfPageView, EditProfPageView, CreateProfilePageView

from . import views

urlpatterns = [
	
	path('register/', UserRegisterView.as_view(), name = 'register'),
     path('login/', CustomLoginView.as_view(), name = 'login'),

	#path('password/', auth_views.PasswordChangeViews.as_view(template_name = 'registration/change_password')),
	path('password/', PasswordsChangeView.as_view(template_name = 'registration/change_password.html'), name = "password_change"),
	path('password_success', views.password_success, name = "password_success"),
	path('<int:pk>/profile/', ShowProfPageView.as_view(), name = 'show_profile_page'),
	path('<int:pk>/edit_profile_page/', EditProfPageView.as_view(), name = 'edit_profile_page'),
	# path('<int:pk>/delete_profile_page/', DeleteProfPageView.as_view(), name = 'delete_profile_page'),
	path('create_profile_page/', CreateProfilePageView.as_view(), name = 'create_profile_page'),
	path('success/', success, name = 'success'),
     path('error_form/', err, name = 'err'),

	path('<int:pk>/delete_pic/', delete_pic, name = 'delete_pic'),


    # Password Reset
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='commons/password-reset/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/',
         auth_view.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
         ),
         name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_view.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
     path('edit_profile/', UserEditView.as_view(), name = 'edit_profile'),

]

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
from django.contrib.auth.forms import PasswordResetForm,UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from app.models import PImg
from typing import Final
from django.contrib.auth.tokens import default_token_generator 
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm

# class LoginForm(AuthenticationForm):
# 	id_username = forms.CharField(
# 		label='',
# 			widget=forms.TextInput(
# 			attrs = {
# 				'placeholder': 'username or emaildwdwdwdwd',
# 			}
# 		)
# 	)
# 	id_password = forms.CharField(
# 		label='', 
# 		widget=forms.PasswordInput(
# 			attrs = {
# 				'placeholder': 'password'
# 			}
# 		)
# 	)
# 	def clean(self):
# 		cleaned_data = super(LoginForm, self).clean()
# 		id_username = self.cleaned_data.get('id_username')
# 		id_username = id_username.lower()	
# 		id_password = self.cleaned_data.get('id_password')
# 		cleaned_data["id_username"] = id_username		
# 		cleaned_data["id_password"] = id_password
# 		return self.cleaned_data

class LoginForm(AuthenticationForm):
	username = forms.CharField(
		label='',
			widget=forms.TextInput(
			attrs = {
				'placeholder': 'username or emaildwdwdwdwd',
			}
		)
	)
	password = forms.CharField(
		label='', 
		widget=forms.PasswordInput(
			attrs = {
				'placeholder': 'password'
			}
		)
	)

class SignUpForm(UserCreationForm):
	email = forms.EmailField(widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email...'}))
	
	class Meta:
		model = User
		fields = ('username', 'email','password1','password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'user name...'
			
		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'password...'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'type the password again...'
	
	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()
		email = self.cleaned_data.get('email')
		email = email.lower()
		username = self.cleaned_data.get('username')
		username = username.lower()
		username_len=len(str(username))
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		err=[]

		cleaned_data["username"] = username
		cleaned_data["email"] = email
		cleaned_data["password1"] = password1
		cleaned_data["password2"] = password2

		if User.objects.filter(username=username).exists() and User.objects.filter(email=email).exists():
			raise ValidationError("Email and Username already registered, please try again!")
		elif User.objects.filter(email=email).exists():
			raise ValidationError("Email already registered, please try to log in!")
		elif User.objects.filter(username=username).exists():
			raise ValidationError("Username already exists! Please select a different one")
		elif username == 'admin':
			raise ValidationError("Not allowed! Please choose a different name")
		elif username_len<4:
			# er5 = "Username too short, please use 4 characters or more"	
			# err.append(er5)
			raise ValidationError("Username too short, please use 4 characters or more")		
		return self.cleaned_data

class PasswordChangingForm(PasswordChangeForm):
	old_password = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
	new_password1 = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
	new_password2 = forms.CharField(max_length = 100, widget = forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

	class Meta:
		model = User
		fields = ('old_password', 'new_password1','new_password2')

class EditPForm(UserChangeForm):
	email = forms.EmailField(widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email...', 'type': 'hidden'}))
	username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={'class': 'form-control'}))

	class Meta:
		model = User
		fields = ('username', 'email','password')
		

class ProfilePageForm(forms.ModelForm):
	class Meta: 
		model = PImg
		fields = ('image',)

		def clean(self):
			 cleaned_data = super(ProfilePageForm, self).clean()
			 field2 = cleaned_data.get('image')
			 if field2 is not None:
			 	return cleaned_data
			 else:
			 	return redirect(reverse('err'))
			 	#self.add_error(None, ValidationError('field can not be empty'))

user_auth/templates/commons/password-reset/password_reset.html
{% extends 'base.html' %}

{% block title %}Change Password Page{% endblock title %}

{% block content %} 
<br><br>
<div class="hana_div text-center">
    <div class="card-body">
        <h2>Forgot your username or your password?</h2>
        <hr>
        <div class="alert alert-info" style="background-color:blue_hana_light; text-align: left; z-index: -20; ">
            Can-do's-ville! Enter your registration email to receive your username and instructions for password reset
        </div>
        <form method="post" >
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div >
              <input style = type="email" name="email" autocomplete="email" maxlength="254" required id="id_email" placeholder="email..." class="form-control">
            </div><br/>
            <button class ="btn btn-dark " type="submit" value="Reset Password">Reset</button>&nbsp;
            <a href="{% url 'home' %}" class ="btn btn-light"> Back</a> <br/>  &nbsp; 

            <!-- <input class="btn btn-primary btn-dark" type="submit" value="Reset Password"> -->

        </form>

        <hr>
    </div>
</div>

<script>
  function done(){
    window.location.href = "{% url 'password_reset_done' %}";
  }
</script>

{% endblock content %}

user_auth/templates/commons/password-reset/password_reset_complete.html
{% extends 'base.html' %}
{% block title %} CHEEKY | Change Password {% endblock %}

{% block content %}


<br><br>

            <div class="hana_div text-center">
                <div class="card-body">
                    <h2>Password Reset Complete</h2>
                    <hr>
                    <div class="alert alert-info" style="background-color:blue_hana_light;z-index: -20;  ">
                        Your password reset is successful. Log in with new credentials
                    </div>
                     <a href="{% url 'login' %}" class ="btn btn-dark"> Login</a> <br/>  &nbsp; 
                    
                    <br/>
                    <hr>
                </div>
            </div>



{% endblock %}

user_auth/templates/commons/password-reset/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %} CHEEKY | Change Password {% endblock %}

{% block content %}

<br><br>


           <div class="hana_div">
                <div class="card-body">
                    <h2>INPUT YOUR NEW PASSWORD</h2>
                    <hr>
                    <div class ="form-group text-center">
                    <form method="POST">
                        {% csrf_token %}

                            <label for="id_new_password1" class="text-center">New password:</label> <br/>
                            <input style="text-align:left; " type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1" placeholder="password 1..." class="form-control">

                            <label for="id_new_password2" >Confirm new password:</label> <br/>
                            <input style="text-align:left;"  type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2" placeholder="password 1..." class="form-control">
                        <br/>

                        <div class="alert alert-info" style="background-color:blue_hana_light;  text-align: left;z-index: -20; ">
                            <span class="helptext">
                            <ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters</li><li>Your password can’t be a commonly used password</li><li>Your password can’t be entirely numeric</li></ul>
                            </span>
                        </div>

                        <!-- <input class="btn btn-primary btn-dark" type="submit" value="Reset Password Confirm"> -->
                        <button class ="btn btn-dark " type="submit" value="Reset Password Confirm">Reset Password Confirm</button>&nbsp;

                    </form>
                   
                    <hr>
                </div>

            </div>




{% endblock %}

user_auth/templates/commons/password-reset/password_reset_done.html
{% extends 'base.html' %}
{% block title %} CHEEKY | Change Password {% endblock %}

{% block content %}


            <div class="hana_div text-center">
                <div class="card-body">
                    <h4>RESET INSTRUCTIONS SENT</h4>
                    <hr>
                    <div class="alert alert-info" style="background-color:blue_hana_light; text-align: left;z-index: -20; ">
                        An email with instructions for password reset has been sent to the email you provided. 
                        <br/>
                        <b>Please check your spam folder as well as inbox</b>
                    </div>
                    <hr>
                </div>
            </div>

<script>
  window.setTimeout(function(){
    window.location.href = "{% url 'home' %}";
  }, 3000);
</script>

{% endblock %}

user_auth/templates/commons/password-reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hello!{% endblocktrans %}
{% trans "You're receiving this email because you requested a password reset for your user account at CHEEKY CV." %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The CHEEKY CV Team{% endblocktrans %}

{% endautoescape %}